package service

import "errors"

var (
	ErrTicketStringEmpty = errors.New("ticket string is required")
	ErrUpstreamRequest   = errors.New("failed to request upstream API")
	ErrUpstreamResponse  = errors.New("failed to read upstream response")

	ErrLicensePatentEmpty      = errors.New("license_patent is required")
	ErrCodeEmpty               = errors.New("code is required")
	ErrInvalidCode             = errors.New("code must be a valid integer")
	ErrPlatformLookup          = errors.New("failed to look up platform")
	ErrPlatformMissingTerminal = errors.New("platform is not associated with a bus terminal")
	ErrNotification            = errors.New("failed to send notification")

	ErrEmailAlreadyExists  = errors.New("email already exists")
	ErrDNIAlreadyExists    = errors.New("dni already exists")
	ErrInvalidCredentials  = errors.New("invalid email or password")
	ErrInvalidRefreshToken = errors.New("invalid or expired refresh token")
	ErrUserNotFound        = errors.New("user not found")
	ErrRolNotFound         = errors.New("role not found")
	ErrTerminalNotFound    = errors.New("terminal not found")
	ErrPlatformNotFound    = errors.New("platform not found")
	ErrCityNotFound        = errors.New("city not found")
	ErrTerminalNotOwned    = errors.New("terminal not associated with admin")
	ErrCannotDemoteSelf    = errors.New("cannot demote yourself")
	ErrAlreadyAdmin        = errors.New("user is already admin")
	ErrNotAdmin            = errors.New("user is not admin")
	ErrAlreadySuperAdmin   = errors.New("user is already super admin")
	ErrNotSuperAdmin       = errors.New("user is not super admin")
	ErrMissingFields       = errors.New("missing required fields")
	ErrCityAlreadyExists   = errors.New("city with this postal code already exists")

	ErrNotificationTypeInvalid          = errors.New("notification type must be LOCAL or GLOBAL")
	ErrNotificationMessageEmpty         = errors.New("payload.message is required")
	ErrNotificationGlobalSuperAdminOnly = errors.New("notification type GLOBAL is only allowed for super_admin")
	ErrNotificationPayloadInvalidJSON   = errors.New("payload must be valid JSON")
	ErrNotificationPayloadEmpty         = errors.New("payload is required")
	ErrUnsupportedNotificationRole      = errors.New("unsupported role for notification types")
	ErrTerminalUUIDRequired             = errors.New("query terminaluuid is required for super_admin")
	ErrTerminalUUIDRequiredMultiAdmin   = errors.New("query terminaluuid is required when admin has more than one terminal")
	ErrAdminNoTerminal                  = errors.New("admin has no associated terminal")
	ErrInvalidTerminalUUID              = errors.New("invalid terminaluuid")

	ErrExternalTerminalIDRequired       = errors.New("external_terminal_id is required")
	ErrInvalidExternalTerminalID        = errors.New("invalid external_terminal_id")
	ErrExternalTerminalIDAlreadyUsed    = errors.New("external_terminal_id is already registered")

	ErrBusDelayTypeInvalid           = errors.New("type must be BUS_DELAY")
	ErrBusDelayLicensePatentRequired = errors.New("license_patent is required")
	ErrBusDelayStartDateRequired     = errors.New("start_date is required")
	ErrBusDelayTimeDelayInvalid      = errors.New("payload.time_delay must be a positive integer")
	ErrBusDelayTerminalUUIDRequired  = errors.New("uuid_terminal is required")
	ErrExternalTerminalNotConfigured = errors.New("terminal has no external_terminal_id configured")
	ErrTripNotRegistered             = errors.New("trip is not registered in the terminal system; notification cannot be sent")

	ErrCameraNotificationTypeInvalid = errors.New("type incorrect or missing")
	ErrCodeCameraEmpty               = errors.New("code_camera is required")
	ErrCodeCameraInvalid             = errors.New("code_camera must be a valid integer")
	ErrCameraErrorMessageEmpty       = errors.New("payload.message is required")
)
